# Generated by Django 3.2 on 2024-02-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aEmail', models.EmailField(max_length=254, unique=True)),
                ('aCNumber', models.IntegerField()),
                ('aAddress', models.CharField(max_length=255)),
            ],
        ),
    ]
