# Generated by Django 3.2 on 2024-02-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('cnumber', models.IntegerField()),
                ('birthday', models.DateField()),
                ('sex', models.CharField(max_length=255)),
                ('jobTitle', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
