# Generated by Django 3.2 on 2024-02-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0002_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='jobTitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
