# Generated by Django 3.2 on 2024-02-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0002_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='aVisitType',
            field=models.CharField(default='', max_length=255),
        ),
    ]
