# Generated by Django 3.2 on 2024-02-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0003_auto_20240210_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='cnumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='staff',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='jobTitle',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lname',
            field=models.CharField(max_length=100),
        ),
    ]
