# Generated by Django 3.2 on 2024-02-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0004_auto_20240210_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('General Ward', 'General Ward')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='jobTitle',
            field=models.CharField(choices=[('General Practitioner', 'General Practitioner'), ('Dermatologist', 'Dermatologist'), ('Pediatrician', 'Pediatrician'), ('Head Nurse', 'Head Nurse'), ('Nurse Assistant', 'Nurse Assistant')], max_length=20),
        ),
    ]
