# Generated by Django 3.2 on 2024-02-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0005_auto_20240210_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse')], max_length=10, null=True),
        ),
    ]
