# Generated by Django 3.2 on 2024-02-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0006_staff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aDate', models.DateField()),
                ('aTime', models.TimeField()),
                ('aName', models.CharField(max_length=255)),
                ('aVisitType', models.CharField(default='', max_length=255)),
                ('aStatus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aEmail', models.EmailField(max_length=254, unique=True)),
                ('aCNumber', models.IntegerField()),
                ('aAddress', models.CharField(max_length=255)),
            ],
        ),
    ]
