# Generated by Django 3.2 on 2024-02-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0007_appointment_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='jobTitle',
            new_name='specialization',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='staff',
            name='cnumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
