# Generated by Django 4.1.2 on 2024-03-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0008_auto_20240219_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='clinicaddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='clinicname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
