# Generated by Django 3.2 on 2024-03-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0009_staff_clinicaddress_staff_clinicname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='clinicaddress',
            new_name='clinic',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='clinicname',
        ),
    ]
