# Generated by Django 3.2 on 2024-03-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0010_auto_20240308_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='cnumber',
        ),
    ]
