# Generated by Django 3.2 on 2024-03-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0011_remove_staff_cnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
    ]
