# Generated by Django 3.2 on 2024-03-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0011_remove_staff_cnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_days', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('morning_start', models.TimeField()),
                ('morning_end', models.TimeField()),
                ('afternoon_start', models.TimeField()),
                ('afternoon_end', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
    ]
