# Generated by Django 3.2 on 2024-03-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0012_auto_20240314_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=models.CharField(choices=[('General Practitioner', 'General Practitioner'), ('Dermatologist', 'Dermatologist'), ('Pediatrician', 'Pediatrician'), ('Head Nurse', 'Head Nurse'), ('Bedside Nurse', 'Bedside Nurse')], max_length=20),
        ),
    ]
