# Generated by Django 3.2 on 2024-03-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0013_alter_staff_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='clinic',
        ),
    ]
