# Generated by Django 3.2 on 2024-03-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0014_remove_staff_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=models.CharField(choices=[('General Practitioner', 'General Practitioner'), ('Dermatologist', 'Dermatologist'), ('Pediatrician', 'Pediatrician'), ('Charge Nurse', 'Charge Nurse'), ('Bedside Nurse', 'Bedside Nurse')], max_length=20),
        ),
    ]
