# Generated by Django 4.1.2 on 2024-03-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0015_alter_staff_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('medicationname', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('route', models.CharField(choices=[('Oral', 'Oral'), ('Injection', 'Injection'), ('Topical', 'Topical')], max_length=20, null=True)),
                ('frequency', models.CharField(choices=[('Once Daily', 'Once Daily'), ('Twice Daily', 'Twice Daily'), ('Thrice Daily', 'Thrice Daily')], max_length=20, null=True)),
                ('additionalremarks', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('additional_remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
