# Generated by Django 4.1.2 on 2024-03-31 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0016_medications_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=models.CharField(choices=[('General Practitioner', 'General Practitioner'), ('Pediatrician', 'Pediatrician'), ('Charge Nurse', 'Charge Nurse')], max_length=20),
        ),
    ]
