# Generated by Django 3.2 on 2024-07-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0017_alter_staff_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=models.CharField(choices=[('General Practitioner', 'General Practitioner'), ('Pulmonologist', 'Pulmonologist'), ('Pediatrician', 'Pediatrician')], max_length=20),
        ),
    ]
