# Generated by Django 3.2 on 2024-07-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0019_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
