# Generated by Django 3.2 on 2024-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0020_auto_20240710_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='patient_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
