# Generated by Django 4.1.2 on 2024-07-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0021_alter_notification_created_at'),
        ('hmis', '0022_notification_is_read'),
    ]

    operations = [
    ]
