# Generated by Django 4.1.2 on 2024-07-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0023_merge_20240711_1413'),
        ('hmis', '0023_merge_20240711_1414'),
    ]

    operations = [
    ]
