# Generated by Django 3.2 on 2024-07-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0024_merge_20240711_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
