"""
Django settings for hospital_management project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import firebase_admin
from firebase_admin import credentials
import pyrebase
import pytesseract
from paddleocr import PaddleOCR
from hmis.database import connect_to_mongodb

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=v%59ij1az7yn+iihh6h$b#0td!j=&-i&!iqv=s@=z5k^(30bs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'hmis',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hospital_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hospital_management.wsgi.application'
ASGI_APPLICATION = 'hospital_management.asgi.application'

# Firebase Configuration
#FIREBASE_CONFIG_FILE = 'firebase_config.json'
#cred = credentials.Certificate(FIREBASE_CONFIG_FILE)
#firebase_admin.initialize_app(cred)
config={
    "apiKey": "AIzaSyC0JRWGF4OsRL7-OrsP6F7G15Np5MJzjs4",
   "authDomain": "hmis-a3bbe.firebaseapp.com",
    "databaseURL": "https://hmis-a3bbe-default-rtdb.asia-southeast1.firebasedatabase.app",
    "projectId": "hmis-a3bbe",
    "storageBucket": "hmis-a3bbe.appspot.com",
    "messagingSenderId": "796086831145",
    "appId": "1:796086831145:web:8c4e1406b3bf17f875f438",
    "measurementId": "G-GWES7Z6T2N"
}
firebase=pyrebase.initialize_app(config)
auth = firebase.auth()
database=firebase.database()
#firestore=firebase.firestore()
storage = firebase.storage()

# Initialize Firestore
#firestore_db = firestore.Client()

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'mongodb': {
        'ENGINE': 'djongo',
        'NAME': 'pharmacy',
        'CLIENT': {
            'host': 'pharmacy.h3k6bxm.mongodb.net',
            'port': 27017,
            'username': 'admin',
            'password': 'Qvr4tlGx4qFPdgoU',
            'authSource': 'pharmacy',
            'authMechanism': 'SCRAM-SHA-1',
        },
    }
}

collection = connect_to_mongodb()



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jmmojica0701@gmail.com'
EMAIL_HOST_PASSWORD = 'bnny bwpl rnmd orkp'

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
